//! Enum of all official Touhou artbooks.
//!
//! src: https://en.touhouwiki.net/wiki/Official_Literature

// DO NOT EDIT THIS FILE BY HANDS!
// INSTEAD EDIT CORRESPONDING FILE!

use crate::to_str::ToStr;

#[allow(non_camel_case_types, dead_code)]
#[derive(Debug)]
pub enum Artbook {
	Bohemian_Archive_in_Japanese_Red,
	Seasonal_Dream_Vision,
	Perfect_Memento_in_Strict_Sense,
	The_Grimoire_of_Marisa,
	Symposium_of_Post_mysticism,
	Alternative_Facts_in_Eastern_Utopia,
	The_Grimoire_of_Usami,
}

impl ToStr for Artbook {
	fn to_str(&self) -> &str {
		match self {
			Self::Bohemian_Archive_in_Japanese_Red => "Bohemian Archive in Japanese Red",
			Self::Seasonal_Dream_Vision => "Seasonal Dream Vision",
			Self::Perfect_Memento_in_Strict_Sense => "Perfect Memento in Strict Sense",
			Self::The_Grimoire_of_Marisa => "The Grimoire of Marisa",
			Self::Symposium_of_Post_mysticism => "Symposium of Post-mysticism",
			Self::Alternative_Facts_in_Eastern_Utopia => "Alternative Facts in Eastern Utopia",
			Self::The_Grimoire_of_Usami => "The Grimoire of Usami",
		}
	}
}
