//! Enum of all official Touhou characters.
//!
//! src: https://en.touhouwiki.net/wiki/Characters

// DO NOT EDIT THIS FILE BY HANDS!
// INSTEAD EDIT CORRESPONDING FILE!

use crate::to_str::ToStr;

#[allow(non_camel_case_types, dead_code)]
pub enum Character {
	Unknown,

	// Protagonists
	Reimu_Hakurei,
	Marisa_Kirisame,
	// this is tmp, 'll've to solve it somehow later
	Marisa_Kirisame_and_Alice_Margatroid,

	//
	// PC-98
	//

	// Highly Responsive to Prayers
	SinGyoku,
	YuugenMagan,
	Elis,
	Sariel,
	Mima,
	Kikuri,
	Konngara,

	// the Story of Eastern Wonderland
	Genjii,
	Rika,
	Noroiko,
	Meira,
	Two_Red_Dots,
	Blood_Vessel_Yin_Yang_Orbs,
	Five_Magic_Stones,
	Matenshi,
	Evil_Eye_Sigma,

	// Phantasmagoria of Dim.Dream
	Ellen,
	Kotohime,
	Kana_Anaberal,
	Rikako_Asakura,
	Chiyuri_Kitashirakawa,
	Yumemi_Okazaki,
	//Sokrates
	//Ruukoto
	//Multi
	//Mimi-Chan

	// Lotus Land Story
	Bewitching_Lotus_Flower,
	Orange,
	Kurumi,
	Dark_Mirror,
	Elly,
	Hikariko,
	Yuuka_Kazami,
	Mysterious_Orb,
	Mugetsu,
	Gengetsu,

	// Mystic Square
	Wheel_Demon,
	Sara,
	Spirit_Mirror,
	Louise,
	Alice_Margatroid,
	Yuki,
	Mai,
	Ayana,
	Yumeko,
	Shinki,
	Trump_King,
	//Unnamed cat on cover
	//Unnamed Makai residents in Reimu's Ending

	//
	// Windows 1st Generation
	//

	// Embodiment of Scarlet Devil
	Rumia,
	Daiyousei,
	Cirno,
	Hong_Meiling,
	Koakuma,
	Patchouli_Knowledge,
	Sakuya_Izayoi,
	Remilia_Scarlet,
	Flandre_Scarlet,
	//Rin Satsuki

	// Perfect Cherry Blossom
	Letty_Whiterock,
	Chen,
	Lily_White,
	Prismriver_Sisters,
	Lyrica_Prismriver,
	Lunasa_Prismriver,
	Merlin_Prismriver,
	Youmu_Konpaku,
	Yuyuko_Saigyouji,
	Ran_Yakumo,
	Yukari_Yakumo,
	//Shanghai Doll
	//Hourai Doll
	//Layla Prismriver
	//Youki Konpaku
	//Saigyou Ayakashi

	// Immaterial and Missing Power
	Suika_Ibuki,

	// Imperishable Night
	Wriggle_Nightbug,
	Mystia_Lorelei,
	Keine_Kamishirasawa,
	Tewi_Inaba,
	Reisen_Udongein_Inaba,
	Eirin_Yagokoro,
	Kaguya_Houraisan,
	Fujiwara_no_Mokou,

	// Phantasmagoria of Flower View
	Aya_Shameimaru,
	Medicine_Melancholy,
	Komachi_Onozuka,
	//Eiki Shiki Yamaxanadu
	Eiki_Shiki,

	//
	// Windows 2nd Generation
	//

	// Mountain of Faith
	Shizuha_Aki,
	Minoriko_Aki,
	Hina_Kagiyama,
	Nitori_Kawashiro,
	Momiji_Inubashiri,
	Sanae_Kochiya,
	Kanako_Yasaka,
	Suwako_Moriya,
	//Tenma
	//Mishaguji

	// Scarlet Weather Rhapsody
	Iku_Nagae,
	Tenshi_Hinanawi,

	// Subterranean Animism
	Kisume,
	Yamame_Kurodani,
	Parsee_Mizuhashi,
	Yuugi_Hoshiguma,
	Satori_Komeiji,
	Rin_Kaenbyou,
	Utsuho_Reiuji,
	Koishi_Komeiji,

	// Undefined Fantastic Object
	Nazrin,
	Kogasa_Tatara,
	Ichirin_Kumoi,
	Unzan,
	Minamitsu_Murasa,
	Shou_Toramaru,
	Byakuren_Hijiri,
	Nue_Houjuu,
	//Bishamonten
	//Myouren Hijiri

	// Touhou Hisoutensoku
	Goliath_Doll,
	Giant_Catfish,
	//Hisoutensoku
	//Taisui Xingjun

	// Double Spoiler
	Hatate_Himekaidou,

	// Ten Desires
	Kyouko_Kasodani,
	Yoshika_Miyako,
	Seiga_Kaku,
	Soga_no_Tojiko,
	Mononobe_no_Futo,
	Toyosatomimi_no_Miko,
	Mamizou_Futatsuiwa,

	// Hopeless Masquerade
	Hata_no_Kokoro,

	//
	// Windows 3rd Generation
	//

	// Double Dealing Character
	Wakasagihime,
	Sekibanki,
	Kagerou_Imaizumi,
	Benben_Tsukumo,
	Yatsuhashi_Tsukumo,
	Seija_Kijin,
	Shinmyoumaru_Sukuna,
	Raiko_Horikawa,

	// Urban Legend in Limbo
	Sumireko_Usami,

	// Legacy of Lunatic Kingdom
	Seiran,
	Ringo,
	Doremy_Sweet,
	Sagume_Kishin,
	Clownpiece,
	Junko,
	Hecatia_Lapislazuli,

	// Antinomy of Common Flowers
	Joon_Yorigami,
	Shion_Yorigami,

	// Hidden Star in Four Seasons
	Eternity_Larva,
	Nemuno_Sakata,
	Aunn_Komano,
	Narumi_Yatadera,
	Satono_Nishida,
	Mai_Teireida,
	Okina_Matara,

	// Wily Beast and Weakest Creature
	Eika_Ebisu,
	Urumi_Ushizaki,
	Kutaka_Niwatari,
	Yachie_Kicchou,
	Mayumi_Joutouguu,
	Keiki_Haniyasushin,
	Saki_Kurokoma,

	// Touhou Gouyoku Ibun
	Yuuma_Toutetsu,

	// Unconnected Marketeers
	Mike_Goutokuji,
	Takane_Yamashiro,
	Sannyo_Komakusa,
	Misumaru_Tamatsukuri,
	Tsukasa_Kudamaki,
	Megumu_Iizunamaru,
	Chimata_Tenkyuu,
	Momoyo_Himemushi,

	// Unfinished Dream of All Living Ghost
	Son_Biten,
	Enoko_Mitsugashira,
	Chiyari_Tenkajin,
	Hisami_Yomotsu,
	Zanmu_Nippaku,

	//
	// Print Works
	//

	// Touhou Kourindou
	Rinnosuke_Morichika,
	Tokiko,
	Marisas_unnamed_father,

	// Touhou Sangetsusei
	//Three Mischievous Fairies
	Three_Fairies_of_Light,
	Luna_Child,
	Star_Sapphire,
	Sunny_Milk,
	Tsuchinoko,
	Sake_Bug,
	Unnamed_bake_danuki,
	Unnamed_okuri_inu,

	// Touhou Bougetsushou
	Reisen,
	Gateguards_of_the_Lunar_Capital,
	Watatsuki_no_Toyohime,
	Watatsuki_no_Yorihime,
	Change,
	Lord_Tsukuyomi,
	Mizue_no_Uranoshimako,
	Iwakasa,
	Konohana_Sakuyahime,
	Iwanagahime,

	// Touhou Ibarakasen
	Kasen_Ibaraki,
	Koutei,
	Mukou,
	Shirou_Sendai,
	Unnamed_kuda_gitsune,
	Kume,
	Kanda,
	Houso,
	Suiki,
	Unshou,

	// Touhou Suzunaan
	Kosuzu_Motoori,
	Kosuzus_Grandfather,
	Unnamed_Fox_Student,
	Unnamed_Snake_Youkai,
	The_Fortune_teller,
	Anxious_Moustached_Villager,
	Salt_Merchant,
	Tupai,
	Evil_Dragon,

	// Touhou Chireikiden
	Mizuchi_Miyadeguchi,

	// Touhou Suichouka
	Miyoi_Okunoda,
	Geidonteis_Owner,
	Geidontei_Regulars,
	Unnamed_Zashiki_warashi,
	Unnamed_Yamawaro_Gambler,

	// Fanbooks
	Giant_Toad,
	Daitengu,

	//
	// Music CDs
	//
	Unnamed_girl_on_Dolls_in_Pseudo_Paradise_CD_label,
	Unnamed_girl_on_Dolls_in_Pseudo_Paradise_jacket,
	Maribel_Hearn,
	Renko_Usami,
	Hieda_no_Akyuu,
}

impl ToStr for Character {
	fn to_str(&self) -> &str {
		match self {
			Self::Unknown => "Unknown",

			// Protagonists
			Self::Reimu_Hakurei => "Reimu Hakurei",
			Self::Marisa_Kirisame => "Marisa Kirisame",
			// this is tmp, 'll've to solve it somehow later
			Self::Marisa_Kirisame_and_Alice_Margatroid => "Marisa Kirisame and Alice Margatroid",

			//
			// PC-98
			//

			// Highly Responsive to Prayers
			Self::SinGyoku => "SinGyoku",
			Self::YuugenMagan => "YuugenMagan",
			Self::Elis => "Elis",
			Self::Sariel => "Sariel",
			Self::Mima => "Mima",
			Self::Kikuri => "Kikuri",
			Self::Konngara => "Konngara",

			// the Story of Eastern Wonderland
			Self::Genjii => "Genjii",
			Self::Rika => "Rika",
			Self::Noroiko => "Noroiko",
			Self::Meira => "Meira",
			Self::Two_Red_Dots => "Two Red Dots",
			Self::Blood_Vessel_Yin_Yang_Orbs => "Blood-Vessel Yin-Yang Orbs",
			Self::Five_Magic_Stones => "Five Magic Stones",
			Self::Matenshi => "Matenshi",
			Self::Evil_Eye_Sigma => "Evil Eye Σ",

			// Phantasmagoria of Dim.Dream
			Self::Ellen => "Ellen",
			Self::Kotohime => "Kotohime",
			Self::Kana_Anaberal => "Kana Anaberal",
			Self::Rikako_Asakura => "Rikako Asakura",
			Self::Chiyuri_Kitashirakawa => "Chiyuri Kitashirakawa",
			Self::Yumemi_Okazaki => "Yumemi Okazaki",
			//Sokrates
			//Ruukoto
			//Multi
			//Mimi-Chan

			// Lotus Land Story
			Self::Bewitching_Lotus_Flower => "Bewitching Lotus Flower",
			Self::Orange => "Orange",
			Self::Kurumi => "Kurumi",
			Self::Dark_Mirror => "Dark Mirror",
			Self::Elly => "Elly",
			Self::Hikariko => "Hikariko",
			Self::Yuuka_Kazami => "Yuuka Kazami",
			Self::Mysterious_Orb => "Mysterious Orb",
			Self::Mugetsu => "Mugetsu",
			Self::Gengetsu => "Gengetsu",

			// Mystic Square
			Self::Wheel_Demon => "Wheel Demon",
			Self::Sara => "Sara",
			Self::Spirit_Mirror => "Spirit Mirror",
			Self::Louise => "Louise",
			Self::Alice_Margatroid => "Alice Margatroid",
			Self::Yuki => "Yuki",
			Self::Mai => "Mai",
			Self::Ayana => "Ayana",
			Self::Yumeko => "Yumeko",
			Self::Shinki => "Shinki",
			Self::Trump_King => "Trump King",
			//Unnamed cat on cover
			//Unnamed Makai residents in Reimu's Ending

			//
			// Windows 1st Generation
			//

			// Embodiment of Scarlet Devil
			Self::Rumia => "Rumia",
			Self::Daiyousei => "Daiyousei",
			Self::Cirno => "Cirno",
			Self::Hong_Meiling => "Hong Meiling",
			Self::Koakuma => "Koakuma",
			Self::Patchouli_Knowledge => "Patchouli Knowledge",
			Self::Sakuya_Izayoi => "Sakuya Izayoi",
			Self::Remilia_Scarlet => "Remilia Scarlet",
			Self::Flandre_Scarlet => "Flandre Scarlet",
			//Rin Satsuki

			// Perfect Cherry Blossom
			Self::Letty_Whiterock => "Letty Whiterock",
			Self::Chen => "Chen",
			Self::Lily_White => "Lily White",
			Self::Prismriver_Sisters => "Prismriver Sisters",
			Self::Lyrica_Prismriver => "Lyrica Prismriver",
			Self::Lunasa_Prismriver => "Lunasa Prismriver",
			Self::Merlin_Prismriver => "Merlin Prismriver",
			Self::Youmu_Konpaku => "Youmu Konpaku",
			Self::Yuyuko_Saigyouji => "Yuyuko Saigyouji",
			Self::Ran_Yakumo => "Ran Yakumo",
			Self::Yukari_Yakumo => "Yukari Yakumo",
			//Shanghai Doll
			//Hourai Doll
			//Layla Prismriver
			//Youki Konpaku
			//Saigyou Ayakashi

			// Immaterial and Missing Power
			Self::Suika_Ibuki => "Suika Ibuki",

			// Imperishable Night
			Self::Wriggle_Nightbug => "Wriggle Nightbug",
			Self::Mystia_Lorelei => "Mystia Lorelei",
			Self::Keine_Kamishirasawa => "Keine Kamishirasawa",
			Self::Tewi_Inaba => "Tewi Inaba",
			Self::Reisen_Udongein_Inaba => "Reisen Udongein Inaba",
			Self::Eirin_Yagokoro => "Eirin Yagokoro",
			Self::Kaguya_Houraisan => "Kaguya Houraisan",
			Self::Fujiwara_no_Mokou => "Fujiwara no Mokou",

			// Phantasmagoria of Flower View
			Self::Aya_Shameimaru => "Aya Shameimaru",
			Self::Medicine_Melancholy => "Medicine Melancholy",
			Self::Komachi_Onozuka => "Komachi Onozuka",
			//Eiki Shiki Yamaxanadu
			Self::Eiki_Shiki => "Eiki Shiki",

			//
			// Windows 2nd Generation
			//

			// Mountain of Faith
			Self::Shizuha_Aki => "Shizuha Aki",
			Self::Minoriko_Aki => "Minoriko Aki",
			Self::Hina_Kagiyama => "Hina Kagiyama",
			Self::Nitori_Kawashiro => "Nitori Kawashiro",
			Self::Momiji_Inubashiri => "Momiji Inubashiri",
			Self::Sanae_Kochiya => "Sanae Kochiya",
			Self::Kanako_Yasaka => "Kanako Yasaka",
			Self::Suwako_Moriya => "Suwako Moriya",
			//Tenma
			//Mishaguji

			// Scarlet Weather Rhapsody
			Self::Iku_Nagae => "Iku Nagae",
			Self::Tenshi_Hinanawi => "Tenshi Hinanawi",

			// Subterranean Animism
			Self::Kisume => "Kisume",
			Self::Yamame_Kurodani => "Yamame Kurodani",
			Self::Parsee_Mizuhashi => "Parsee Mizuhashi",
			Self::Yuugi_Hoshiguma => "Yuugi Hoshiguma",
			Self::Satori_Komeiji => "Satori Komeiji",
			Self::Rin_Kaenbyou => "Rin Kaenbyou",
			Self::Utsuho_Reiuji => "Utsuho Reiuji",
			Self::Koishi_Komeiji => "Koishi Komeiji",

			// Undefined Fantastic Object
			Self::Nazrin => "Nazrin",
			Self::Kogasa_Tatara => "Kogasa Tatara",
			Self::Ichirin_Kumoi => "Ichirin Kumoi",
			Self::Unzan => "Unzan",
			Self::Minamitsu_Murasa => "Minamitsu Murasa",
			Self::Shou_Toramaru => "Shou Toramaru",
			Self::Byakuren_Hijiri => "Byakuren Hijiri",
			Self::Nue_Houjuu => "Nue Houjuu",
			//Bishamonten
			//Myouren Hijiri

			// Touhou Hisoutensoku
			Self::Goliath_Doll => "Goliath Doll",
			Self::Giant_Catfish => "Giant Catfish",
			//Hisoutensoku
			//Taisui Xingjun

			// Double Spoiler
			Self::Hatate_Himekaidou => "Hatate Himekaidou",

			// Ten Desires
			Self::Kyouko_Kasodani => "Kyouko Kasodani",
			Self::Yoshika_Miyako => "Yoshika Miyako",
			Self::Seiga_Kaku => "Seiga Kaku",
			Self::Soga_no_Tojiko => "Soga no Tojiko",
			Self::Mononobe_no_Futo => "Mononobe no Futo",
			Self::Toyosatomimi_no_Miko => "Toyosatomimi no Miko",
			Self::Mamizou_Futatsuiwa => "Mamizou Futatsuiwa",

			// Hopeless Masquerade
			Self::Hata_no_Kokoro => "Hata no Kokoro",

			//
			// Windows 3rd Generation
			//

			// Double Dealing Character
			Self::Wakasagihime => "Wakasagihime",
			Self::Sekibanki => "Sekibanki",
			Self::Kagerou_Imaizumi => "Kagerou Imaizumi",
			Self::Benben_Tsukumo => "Benben Tsukumo",
			Self::Yatsuhashi_Tsukumo => "Yatsuhashi Tsukumo",
			Self::Seija_Kijin => "Seija Kijin",
			Self::Shinmyoumaru_Sukuna => "Shinmyoumaru Sukuna",
			Self::Raiko_Horikawa => "Raiko Horikawa",

			// Urban Legend in Limbo
			Self::Sumireko_Usami => "Sumireko Usami",

			// Legacy of Lunatic Kingdom
			Self::Seiran => "Seiran",
			Self::Ringo => "Ringo",
			Self::Doremy_Sweet => "Doremy Sweet",
			Self::Sagume_Kishin => "Sagume Kishin",
			Self::Clownpiece => "Clownpiece",
			Self::Junko => "Junko",
			Self::Hecatia_Lapislazuli => "Hecatia Lapislazuli",

			// Antinomy of Common Flowers
			Self::Joon_Yorigami => "Joon Yorigami",
			Self::Shion_Yorigami => "Shion Yorigami",

			// Hidden Star in Four Seasons
			Self::Eternity_Larva => "Eternity Larva",
			Self::Nemuno_Sakata => "Nemuno Sakata",
			Self::Aunn_Komano => "Aunn Komano",
			Self::Narumi_Yatadera => "Narumi Yatadera",
			Self::Satono_Nishida => "Satono Nishida",
			Self::Mai_Teireida => "Mai Teireida",
			Self::Okina_Matara => "Okina Matara",

			// Wily Beast and Weakest Creature
			Self::Eika_Ebisu => "Eika Ebisu",
			Self::Urumi_Ushizaki => "Urumi Ushizaki",
			Self::Kutaka_Niwatari => "Kutaka Niwatari",
			Self::Yachie_Kicchou => "Yachie Kicchou",
			Self::Mayumi_Joutouguu => "Mayumi Joutouguu",
			Self::Keiki_Haniyasushin => "Keiki Haniyasushin",
			Self::Saki_Kurokoma => "Saki Kurokoma",

			// Touhou Gouyoku Ibun
			Self::Yuuma_Toutetsu => "Yuuma Toutetsu",

			// Unconnected Marketeers
			Self::Mike_Goutokuji => "Mike Goutokuji",
			Self::Takane_Yamashiro => "Takane Yamashiro",
			Self::Sannyo_Komakusa => "Sannyo Komakusa",
			Self::Misumaru_Tamatsukuri => "Misumaru Tamatsukuri",
			Self::Tsukasa_Kudamaki => "Tsukasa Kudamaki",
			Self::Megumu_Iizunamaru => "Megumu Iizunamaru",
			Self::Chimata_Tenkyuu => "Chimata Tenkyuu",
			Self::Momoyo_Himemushi => "Momoyo Himemushi",

			// Unfinished Dream of All Living Ghost
			Self::Son_Biten => "Son Biten",
			Self::Enoko_Mitsugashira => "Enoko Mitsugashira",
			Self::Chiyari_Tenkajin => "Chiyari Tenkajin",
			Self::Hisami_Yomotsu => "Hisami Yomotsu",
			Self::Zanmu_Nippaku => "Zanmu Nippaku",

			//
			// Print Works
			//

			// Touhou Kourindou
			Self::Rinnosuke_Morichika => "Rinnosuke Morichika",
			Self::Tokiko => "Tokiko",
			Self::Marisas_unnamed_father => "Marisa's unnamed father",

			// Touhou Sangetsusei
			//Three Mischievous Fairies
			Self::Three_Fairies_of_Light => "Three Fairies of Light",
			Self::Luna_Child => "Luna Child",
			Self::Star_Sapphire => "Star Sapphire",
			Self::Sunny_Milk => "Sunny Milk",
			Self::Tsuchinoko => "Tsuchinoko",
			Self::Sake_Bug => "Sake Bug",
			Self::Unnamed_bake_danuki => "Unnamed bake-danuki",
			Self::Unnamed_okuri_inu => "Unnamed okuri-inu",

			// Touhou Bougetsushou
			Self::Reisen => "Reisen",
			Self::Gateguards_of_the_Lunar_Capital => "Gateguards of the Lunar Capital",
			Self::Watatsuki_no_Toyohime => "Watatsuki no Toyohime",
			Self::Watatsuki_no_Yorihime => "Watatsuki no Yorihime",
			Self::Change => "Chang'e",
			Self::Lord_Tsukuyomi => "Lord Tsukuyomi",
			Self::Mizue_no_Uranoshimako => "Mizue no Uranoshimako",
			Self::Iwakasa => "Iwakasa",
			Self::Konohana_Sakuyahime => "Konohana-Sakuyahime",
			Self::Iwanagahime => "Iwanagahime",

			// Touhou Ibarakasen
			Self::Kasen_Ibaraki => "Kasen Ibaraki",
			Self::Koutei => "Koutei",
			Self::Mukou => "Mukou",
			Self::Shirou_Sendai => "Shirou Sendai",
			Self::Unnamed_kuda_gitsune => "Unnamed kuda-gitsune",
			Self::Kume => "Kume",
			Self::Kanda => "Kanda",
			Self::Houso => "Houso",
			Self::Suiki => "Suiki",
			Self::Unshou => "Unshou",

			// Touhou Suzunaan
			Self::Kosuzu_Motoori => "Kosuzu Motoori",
			Self::Kosuzus_Grandfather => "Kosuzu's Grandfather",
			Self::Unnamed_Fox_Student => "Unnamed Fox Student",
			Self::Unnamed_Snake_Youkai => "Unnamed Snake Youkai",
			Self::The_Fortune_teller => "The Fortune-teller",
			Self::Anxious_Moustached_Villager => "Anxious Moustached Villager",
			Self::Salt_Merchant => "Salt Merchant",
			Self::Tupai => "Tupai",
			Self::Evil_Dragon => "Evil Dragon",

			// Touhou Chireikiden
			Self::Mizuchi_Miyadeguchi => "Mizuchi Miyadeguchi",

			// Touhou Suichouka
			Self::Miyoi_Okunoda => "Miyoi Okunoda",
			Self::Geidonteis_Owner => "Geidontei's Owner",
			Self::Geidontei_Regulars => "Geidontei Regulars",
			Self::Unnamed_Zashiki_warashi => "Unnamed Zashiki-warashi",
			Self::Unnamed_Yamawaro_Gambler => "Unnamed Yamawaro Gambler",

			// Fanbooks
			Self::Giant_Toad => "Giant Toad",
			Self::Daitengu => "Daitengu",

			//
			// Music CDs
			//
			Self::Unnamed_girl_on_Dolls_in_Pseudo_Paradise_CD_label => "Unnamed girl on Dolls in Pseudo Paradise CD label",
			Self::Unnamed_girl_on_Dolls_in_Pseudo_Paradise_jacket => "Unnamed girl on Dolls in Pseudo Paradise jacket",
			Self::Maribel_Hearn => "Maribel Hearn",
			Self::Renko_Usami => "Renko Usami",
			Self::Hieda_no_Akyuu => "Hieda no Akyuu",
		}
	}
}
