//! Enum of all official Touhou games.
//!
//! src: https://en.touhouwiki.net/wiki/Touhou_Wiki

// DO NOT EDIT THIS FILE BY HANDS!
// INSTEAD EDIT CORRESPONDING FILE!

use crate::to_str::ToStr;

#[allow(non_camel_case_types, dead_code)]
#[derive(Debug)]
pub enum Game {
	// PC-98 Games
	TH_01__Highly_Responsive_to_Prayers,
	TH_02__Story_of_Eastern_Wonderland,
	TH_03__Phantasmagoria_of_Dim_Dream,
	TH_04__Lotus_Land_Story,
	TH_05__Mystic_Square,

	//
	// Windows Games
	//

	// Windows 1st Generation
	TH_06__Embodiment_of_Scarlet_Devil,
	TH_07__Perfect_Cherry_Blossom,
	TH_07_5__Immaterial_and_Missing_Power,
	TH_08__Imperishable_Night,
	TH_09__Phantasmagoria_of_Flower_View,
	TH_09_5__Shoot_the_Bullet,

	// Windows 2st Generation
	TH_10__Mountain_of_Faith,
	TH_10_5__Scarlet_Weather_Rhapsody,
	TH_11__Subterranean_Animism,
	TH_12__Undefined_Fantastic_Object,
	TH_12_3__Touhou_Hisoutensoku,
	TH_12_5__Double_Spoiler,
	TH_12_8__Fairy_Wars,
	TH_13__Ten_Desires,
	TH_13_5__Hopeless_Masquerade,

	// Windows 3rd Generation
	TH_14__Double_Dealing_Character,
	TH_14_3__Impossible_Spell_Card,
	TH_14_5__Urban_Legend_in_Limbo,
	TH_15__Legacy_of_Lunatic_Kingdom,
	TH_15_5__Antinomy_of_Common_Flowers,
	TH_16__Hidden_Star_in_Four_Seasons,
	TH_16_5__Violet_Detector,
	TH_17__Wily_Beast_and_Weakest_Creature,
	TH_17_5__Sunken_Fossil_World,
	TH_18__Unconnected_Marketeers,
	TH_18_5__100th_Black_Market,
	TH_19__Unfinished_Dream_of_All_Living_Ghost,
}

impl ToStr for Game {
	fn to_str(&self) -> &str {
		match self {
			// PC-98 Games
			Self::TH_01__Highly_Responsive_to_Prayers => "TH 01  Highly Responsive to Prayers",
			Self::TH_02__Story_of_Eastern_Wonderland => "TH 02  Story of Eastern Wonderland",
			Self::TH_03__Phantasmagoria_of_Dim_Dream => "TH 03  Phantasmagoria of Dim.Dream",
			Self::TH_04__Lotus_Land_Story => "TH 04  Lotus Land Story",
			Self::TH_05__Mystic_Square => "TH 05  Mystic Square",

			//
			// Windows Games
			//

			// Windows 1st Generation
			Self::TH_06__Embodiment_of_Scarlet_Devil => "TH 06  Embodiment of Scarlet Devil",
			Self::TH_07__Perfect_Cherry_Blossom => "TH 07  Perfect Cherry Blossom",
			Self::TH_07_5__Immaterial_and_Missing_Power => "TH 07.5  Immaterial and Missing Power",
			Self::TH_08__Imperishable_Night => "TH 08  Imperishable Night",
			Self::TH_09__Phantasmagoria_of_Flower_View => "TH 09  Phantasmagoria of Flower View",
			Self::TH_09_5__Shoot_the_Bullet => "TH 09.5  Shoot the Bullet",

			// Windows 2st Generation
			Self::TH_10__Mountain_of_Faith => "TH 10  Mountain of Faith",
			Self::TH_10_5__Scarlet_Weather_Rhapsody => "TH 10.5  Scarlet Weather Rhapsody",
			Self::TH_11__Subterranean_Animism => "TH 11  Subterranean Animism",
			Self::TH_12__Undefined_Fantastic_Object => "TH 12  Undefined Fantastic Object",
			Self::TH_12_3__Touhou_Hisoutensoku => "TH 12.3  Touhou Hisoutensoku",
			Self::TH_12_5__Double_Spoiler => "TH 12.5  Double Spoiler",
			Self::TH_12_8__Fairy_Wars => "TH 12.8  Fairy Wars",
			Self::TH_13__Ten_Desires => "TH 13  Ten Desires",
			Self::TH_13_5__Hopeless_Masquerade => "TH 13.5  Hopeless Masquerade",

			// Windows 3rd Generation
			Self::TH_14__Double_Dealing_Character => "TH 14  Double Dealing Character",
			Self::TH_14_3__Impossible_Spell_Card => "TH 14.3  Impossible Spell Card",
			Self::TH_14_5__Urban_Legend_in_Limbo => "TH 14.5  Urban Legend in Limbo",
			Self::TH_15__Legacy_of_Lunatic_Kingdom => "TH 15  Legacy of Lunatic Kingdom",
			Self::TH_15_5__Antinomy_of_Common_Flowers => "TH 15.5  Antinomy of Common Flowers",
			Self::TH_16__Hidden_Star_in_Four_Seasons => "TH 16  Hidden Star in Four Seasons",
			Self::TH_16_5__Violet_Detector => "TH 16.5  Violet Detector",
			Self::TH_17__Wily_Beast_and_Weakest_Creature => "TH 17  Wily Beast and Weakest Creature",
			Self::TH_17_5__Sunken_Fossil_World => "TH 17.5  Sunken Fossil World",
			Self::TH_18__Unconnected_Marketeers => "TH 18  Unconnected Marketeers",
			Self::TH_18_5__100th_Black_Market => "TH 18.5  100th Black Market",
			Self::TH_19__Unfinished_Dream_of_All_Living_Ghost => "TH 19  Unfinished Dream of All Living Ghost",
		}
	}
}
